### ISSUE TITLE
dis shit sux

### ISSUE THREAD

**Issue by vinciblu** [datachainlab/cosmos-ethereum-ibc-lcp#35]
ind v1.1.6 (https://github.com/apache/incubator-teaclave-sgx-sdk?rev=v1.1.6#c3d82372)
   Compiling hashbrown_tstd v0.12.0 (https://github.com/apache/incubator-teaclave-sgx-sdk?rev=v1.1.6#c3d82372)
   Compiling sgx_backtrace_sys v1.1.6 (https://github.com/apache/incubator-teaclave-sgx-sdk?rev=v1.1.6#c3d82372)
error[E0432]: unresolved imports `sgx_libc::errno`, `sgx_libc::error_string`, `sgx_libc::set_errno`
   --> /Users/evan/.cargo/git/checkouts/incubator-teaclave-sgx-sdk-c63c8825343e87f0/c3d8237/sgx_trts/src/lib.rs:109:24
    |
109 |     pub use sgx_libc::{errno, error_string, set_errno};
    |                        ^^^^^  ^^^^^^^^^^^^  ^^^^^^^^^ no `set_errno` in the root
    |                        |      |
    |                        |      no `error_string` in the root
    |                        no `errno` in the root

error[E0432]: unresolved import `libc::exit_function_t`
   --> /Users/evan/.cargo/git/checkouts/incubator-teaclave-sgx-sdk-c63c8825343e87f0/c3d8237/sgx_trts/src/trts.rs:182:9
    |
182 | pub use libc::exit_function_t;
    |         ^^^^^^^^^^^^^^^^^^^^^ no `exit_function_t` in the root

error[E0425]: cannot find function `memchr` in crate `sgx_libc`
  --> /Users/evan/.cargo/git/checkouts/incubator-teaclave-sgx-sdk-c63c8825343e87f0/c3d8237/sgx_trts/src/memchr.rs:24:32
   |
24 |     let p = unsafe { sgx_libc::memchr(haystack.as_ptr(), needle, haystack.len()) };
   |                                ^^^^^^ not found in `sgx_libc`
   |
help: consider importing this function
   |
18 | use core::slice::memchr::memchr;
   |
help: if you import `memchr`, refer to it directly
   |
24 -     let p = unsafe { sgx_libc::memchr(haystack.as_ptr(), needle, haystack.len()) };
24 +     let p = unsafe { memchr(haystack.as_ptr(), needle, haystack.len()) };
   |

error[E0425]: cannot find function `memrchr` in crate `sgx_libc`
  --> /Users/evan/.cargo/git/checkouts/incubator-teaclave-sgx-sdk-c63c8825343e87f0/c3d8237/sgx_trts/src/memchr.rs:38:36
   |
38 |         let p = unsafe { sgx_libc::memrchr(haystack.as_ptr(), needle, haystack.len()) };
   |                                    ^^^^^^^ not found in `sgx_libc`
   |
help: consider importing one of these items
   |
18 | use core::slice::memchr::memrchr;
   |
18 | use crate::memchr::memrchr;
   |
help: if you import `memrchr`, refer to it directly
   |
38 -         let p = unsafe { sgx_libc::memrchr(haystack.as_ptr(), needle, haystack.len()) };
38 +         let p = unsafe { memrchr(haystack.as_ptr(), needle, haystack.len()) };
   |

error[E0425]: cannot find function `atexit` in crate `libc`
   --> /Users/evan/.cargo/git/checkouts/incubator-teaclave-sgx-sdk-c63c8825343e87f0/c3d8237/sgx_trts/src/trts.rs:189:30
    |
189 |     let ret = unsafe { libc::atexit(fun) };
    |                              ^^^^^^ not found in `libc`

error[E0658]: use of unstable library feature 'core_intrinsics': intrinsics are unlikely to ever be stabilized, instead they should be used through stabilized interfaces in the rest of the standard library
  --> /Users/evan/.cargo/git/checkouts/incubator-teaclave-sgx-sdk-c63c8825343e87f0/c3d8237/sgx_trts/src/trts.rs:23:5
   |
23 | use core::intrinsics::abort;
   |     ^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: add `#![feature(core_intrinsics)]` to the crate attributes to enable

error[E0658]: use of unstable library feature 'core_intrinsics': intrinsics are unlikely to ever be stabilized, instead they should be used through stabilized interfaces in the rest of the standard library
   --> /Users/evan/.cargo/git/checkouts/incubator-teaclave-sgx-sdk-c63c8825343e87f0/c3d8237/sgx_trts/src/trts.rs:185:14
    |
185 |     unsafe { abort() }
    |              ^^^^^
    |
    = help: add `#![feature(core_intrinsics)]` to the crate attributes to enable

Some errors have detailed explanations: E0425, E0432, E0658.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `sgx_trts` due to 7 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `sgx_unwind v1.1.6 (https://github.com/apache/incubator-teaclave-sgx-sdk?rev=v1.1.6#c3d82372)`

Caused by:
  process didn't exit successfully: `/Users/evan/ibc/enclave/target/release/build/sgx_unwind-a5b70a469209417d/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=/Users/evan/.cargo/git/checkouts/incubator-teaclave-sgx-sdk-c63c8825343e87f0/c3d8237/sgx_unwind/../sgx_unwind/libunwind/src/x86_64/Lapply_reg_state.c
  cargo:rerun-if-changed=/Users/evan/.cargo/git/checkouts/incubator-teaclave-sgx-sdk-c63c8825343e87f0/c3d8237/sgx_unwind/../sgx_unwind/libunwind/src/x86_64/Gos-freebsd.c
  cargo:rerun-if-changed=/Users/evan/.cargo/git/checkouts/incubator-teaclave-sgx-sdk-c63c8825343e87f0/c3d8237/sgx_unwind/../sgx_unwind/libunwind/src/x86_64/Lreg_states_iterate.c
  cargo:rerun-if-changed=/Users/evan/.cargo/git/checkouts/incubator-teaclave-sgx-sdk-c63c8825343e87f0/c3d8237/sgx_unwind/../sgx_unwind/libunwind/src/x86_64/longjmp.S
  cargo:rerun-if-changed=/Users/evan/.cargo/git/checkouts/incubator-teaclave-sgx-sdk-c63c8825343e87f0/c3d8237/sgx_unwind/../sgx_unwind/libunwind/src/x86_64/Gapply_reg_state.c
  cargo:rerun-if-changed=/Users/evan/.cargo/git/checkouts/incubator-teaclave-sgx-sdk-c63c8825343e87f0/c3d8237/sgx_unwind/../sgx_unwind/libunwind/src/x86_64/Lglobal.c
  cargo:rerun-if-changed=/Users/evan/.cargo/git/checkouts/incubator-teaclave-sgx-sdk-c63c8825343e87f0/c3d8237/sgx_unwind/../sgx_unwind/libunwind/src/x86_64/Gresume.c
  cargo:rerun-if-changed=/Users/evan

**Comment by bluele** [comment]
I suggest you try the build steps here with x86 machine: https://github.com/datachainlab/lcp-go/blob/main/.github/workflows/test.yml#L9
